export const initialFormState = {
  name: '',
  coClassfication: '',
  businessNumber: '',
  homepage: '',
  businessType: '',
  businessItem: '',
  representativeName: '',
  commencementDate: '',
  region: '',
  city: '',
  address: '',
  employee: '',
  businessScale: '',
  funnel: '',
};
