// src/features/project/constants/utilizationDummyData.js

/**
 * 투입률 더미 데이터
 */

export const DUMMY_UTILIZATION_DATA = {
  period: {
    start: '2025-01-06',
    end: '2025-01-10',
    workingDays: 5,
  },
  summary: {
    totalUtilization: 75.5,
    totalUsers: 20,
    totalBaseHours: 800, // 20명 × 5일 × 8시간
    totalWorkHours: 604,
  },
  byTeam: [
    {
      teamId: 1,
      teamName: '개발1팀',
      utilization: 82.3,
      memberCount: 5,
      baseHours: 200,
      workHours: 164.6,
      members: [
        {
          userId: 1,
          userName: '홍길동',
          membershipDays: 5,
          baseHours: 40,
          workHours: 16,
          utilization: 40.0,
          status: 'low',
          note: '휴가 또는 저투입 확인 필요',
        },
        {
          userId: 2,
          userName: '김철수',
          membershipDays: 5,
          baseHours: 40,
          workHours: 0,
          utilization: 0,
          status: 'missing_work',
          missingDates: ['2025-01-06', '2025-01-07', '2025-01-08', '2025-01-09', '2025-01-10'],
        },
        {
          userId: 3,
          userName: '이영희',
          membershipDays: 5,
          baseHours: 40,
          workHours: 35,
          utilization: 87.5,
          status: 'normal',
        },
        {
          userId: 4,
          userName: '박민수',
          membershipDays: 3,
          baseHours: 24,
          workHours: 20,
          utilization: 83.3,
          status: 'normal',
          note: '1/8 중도 합류',
        },
        {
          userId: 5,
          userName: '최지훈',
          membershipDays: 5,
          baseHours: 40,
          workHours: 32,
          utilization: 80.0,
          status: 'normal',
        },
      ],
    },
    {
      teamId: 2,
      teamName: '개발2팀',
      utilization: 78.5,
      memberCount: 6,
      baseHours: 240,
      workHours: 188.4,
      members: [
        {
          userId: 6,
          userName: '정수진',
          membershipDays: 5,
          baseHours: 40,
          workHours: 38,
          utilization: 95.0,
          status: 'normal',
        },
        {
          userId: 7,
          userName: '강민호',
          membershipDays: 5,
          baseHours: 40,
          workHours: 35,
          utilization: 87.5,
          status: 'normal',
        },
        {
          userId: 8,
          userName: '윤서연',
          membershipDays: 5,
          baseHours: 40,
          workHours: 32,
          utilization: 80.0,
          status: 'normal',
        },
        {
          userId: 9,
          userName: '임재현',
          membershipDays: 5,
          baseHours: 40,
          workHours: 28,
          utilization: 70.0,
          status: 'normal',
        },
        {
          userId: 10,
          userName: '송하은',
          membershipDays: 5,
          baseHours: 40,
          workHours: 30,
          utilization: 75.0,
          status: 'normal',
        },
        {
          userId: 11,
          userName: '조현우',
          membershipDays: 5,
          baseHours: 40,
          workHours: 25.4,
          utilization: 63.5,
          status: 'normal',
        },
      ],
    },
    {
      teamId: 3,
      teamName: '인프라팀',
      utilization: 68.2,
      memberCount: 4,
      baseHours: 160,
      workHours: 109.12,
      members: [
        {
          userId: 12,
          userName: '한지민',
          membershipDays: 5,
          baseHours: 40,
          workHours: 32,
          utilization: 80.0,
          status: 'normal',
        },
        {
          userId: 13,
          userName: '서준호',
          membershipDays: 5,
          baseHours: 40,
          workHours: 28,
          utilization: 70.0,
          status: 'normal',
        },
        {
          userId: 14,
          userName: '장예린',
          membershipDays: 5,
          baseHours: 40,
          workHours: 26,
          utilization: 65.0,
          status: 'normal',
        },
        {
          userId: 15,
          userName: '배성민',
          membershipDays: 5,
          baseHours: 40,
          workHours: 23.12,
          utilization: 57.8,
          status: 'low',
        },
      ],
    },
    {
      teamId: 4,
      teamName: '디자인팀',
      utilization: 72.0,
      memberCount: 3,
      baseHours: 120,
      workHours: 86.4,
      members: [
        {
          userId: 16,
          userName: '노지은',
          membershipDays: 5,
          baseHours: 40,
          workHours: 32,
          utilization: 80.0,
          status: 'normal',
        },
        {
          userId: 17,
          userName: '유태윤',
          membershipDays: 5,
          baseHours: 40,
          workHours: 28,
          utilization: 70.0,
          status: 'normal',
        },
        {
          userId: 18,
          userName: '권나연',
          membershipDays: 5,
          baseHours: 40,
          workHours: 26.4,
          utilization: 66.0,
          status: 'normal',
        },
      ],
    },
    {
      teamId: 5,
      teamName: '기획팀',
      utilization: 65.5,
      memberCount: 2,
      baseHours: 80,
      workHours: 52.4,
      members: [
        {
          userId: 19,
          userName: '문동혁',
          membershipDays: 5,
          baseHours: 40,
          workHours: 28,
          utilization: 70.0,
          status: 'normal',
        },
        {
          userId: 20,
          userName: '안소희',
          membershipDays: 5,
          baseHours: 40,
          workHours: 24.4,
          utilization: 61.0,
          status: 'normal',
        },
      ],
    },
  ],
};

// 사용자별 투입률 (상위/하위)
export const DUMMY_USER_UTILIZATION = {
  topUsers: [
    { userId: 6, userName: '정수진', teamName: '개발2팀', utilization: 95.0, workHours: 38 },
    { userId: 3, userName: '이영희', teamName: '개발1팀', utilization: 87.5, workHours: 35 },
    { userId: 7, userName: '강민호', teamName: '개발2팀', utilization: 87.5, workHours: 35 },
    { userId: 4, userName: '박민수', teamName: '개발1팀', utilization: 83.3, workHours: 20 },
    { userId: 12, userName: '한지민', teamName: '인프라팀', utilization: 80.0, workHours: 32 },
    { userId: 5, userName: '최지훈', teamName: '개발1팀', utilization: 80.0, workHours: 32 },
    { userId: 8, userName: '윤서연', teamName: '개발2팀', utilization: 80.0, workHours: 32 },
    { userId: 16, userName: '노지은', teamName: '디자인팀', utilization: 80.0, workHours: 32 },
    { userId: 10, userName: '송하은', teamName: '개발2팀', utilization: 75.0, workHours: 30 },
    { userId: 19, userName: '문동혁', teamName: '기획팀', utilization: 70.0, workHours: 28 },
  ],
  bottomUsers: [
    { userId: 2, userName: '김철수', teamName: '개발1팀', utilization: 0, workHours: 0, status: 'missing_work' },
    { userId: 1, userName: '홍길동', teamName: '개발1팀', utilization: 40.0, workHours: 16, status: 'low' },
    { userId: 15, userName: '배성민', teamName: '인프라팀', utilization: 57.8, workHours: 23.12, status: 'low' },
    { userId: 20, userName: '안소희', teamName: '기획팀', utilization: 61.0, workHours: 24.4 },
    { userId: 11, userName: '조현우', teamName: '개발2팀', utilization: 63.5, workHours: 25.4 },
  ],
};
